<?php
    $title = "Receitas";

    $marmitas = array(
        0 => array('id' => 1, 'nome' => 'Frango colorido', 'tamanho' => 'Médio',
        'preco' => 'R$ 15,00', 'img' => 'imgs/img1.png', 
        'ing' => '2 peitos de frango sem osso e sem pele, em cubinhos
        sal e pimenta,
        1 dente de alho picado,
        3 colheres de sopa de óleo,
        ½ xícara de chá de pimentão vermelho em cubinhos,
        ½ xícara de chá de pimentão verde em cubinhos,
        ½ xícara de chá de pimentão amarelo em cubinhos,
        2 tomates sem sementes picados,
        cebolinha picada.'),
        1 => array('id' => 2, 'nome' => 'Estrogonofe de carne', 'tamanho' => 'Pequeno',
        'preco' => 'R$ 12,00', 'img' => 'imgs/img2.png', 
        'ing' => '1 bife de miolo de alcatra (cerca de 150 g),
        100 g de cogumelos-de-paris frescos,
        ½ cebola pequena,
        1 dente de alho,
        1 xícara (chá) de creme de leite fresco,
        ½ colher (sopa) de extrato de tomate,
        ½ colher (sopa) de ketchup,
        1 colher (sopa) de molho inglês,
        ½ colher (sopa) de conhaque,
        1 colher (sopa) de azeite,
        sal e pimenta-do-reino moída.'),
        2 => array('id' => 3, 'nome' => 'Lombo assado com legumes', 'tamanho' => 'Médio',
        'preco' => 'R$ 17,00', 'img' => 'imgs/img3.png', 
        'ing' => '1 laranja espremida,
        1 limão espremido,
        1 colher de sopa de sal,
        1 colher de sopa de molho inglês,
        3 colheres de sopa de mostarda,
        1/3 de xícara de chá de azeite de oliva,
        5 dentes de alho espremidos,
        1 pitada de pimenta-do-reino,
        alecrim,
        1 colher de café de páprica picante,
        1 peça de lombo suíno de (cerca de 1 kg),
        1 kg de batata bolinha,
        1 cenoura picada em bastões e
        1 xícara de chá de vagens picadas.'),
        3 => array('id' => 4, 'nome' => 'Frango com ervilha e saladinha de tomate', 'tamanho' => 'Médio',
        'preco' => 'R$ 15,00', 'img' => 'imgs/img4.png', 
        'ing' => '1 bife de filé de peito de frango (cerca de 150 g),
        ¼ de xícara (chá) de arroz,
        ½ cebola pequena,
        1 dente de alho,
        ⅓ de xícara (chá) de ervilhas congeladas,
        1 tomate maduro,
        1 colher (sopa) de caldo de limão,
        1 pitada de cúrcuma,
        1 pitada de cominho,
        1 talo de cebolinha,
        ½ colher (sopa) de azeite,
        ½ colher (chá) de sal e
        pimenta-do-reino em grãos moída.'),
        5 => array('id' => 6, 'nome' => 'Frango frito com arroz', 'tamanho' => 'Grande',
        'preco' => 'R$ 20,00', 'img' => 'imgs/img5.png', 
        'ing' => '1/2 xícara (chá) de arroz,
        2 colheres de chá de alho picado,
        sal,
        1/2 colher de chá de açúcar,
        1 colher de sopa de gochujang,
        1/3 xícaras de chá de maionese,
        700 gramas de peito de frango sassami,
        1 e 1/2 xícara de chá de farinha de rosca e
        azeite.'),
        6 => array('id' => 7, 'nome' => 'Salada de macarrão, legumes e verduras', 'tamanho' => 'Médio',
        'preco' => 'R$ 14,00', 'img' => 'imgs/img6.png', 
        'ing' => '1 xícara de macarrão gravatinha,
        2 batatas em tiras,
        1 cenoura grande em tiras,
        1 xícara de repolho lavado e em tiras,
        1 xícara de alface lavada e em tiras,
        salsinha,
        2 colheres (sopa) de azeite,
        2 colheres (sopa) de Shoyu (molho de soja),
        2 colheres (sopa) de suco de limão.')
    );
?>